# Can be used if Operator is already installed
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-openshift
  namespace: openshift-gitops
spec:
  destination:
    namespace: monitoring-grafana-dashboards
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/overlays/dashboards
    repoURL: https://github.com/thomas-biesmans/openshift4-grafana.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
