apiVersion: v2
name: base
description: A Helm chart for ArgoCD to deploy Grafana through an Operator
version: 1.0.0
appVersion: 1.0.0

# Deploy custom Grafana from OperatorHub based on this blog:
# https://www.redhat.com/en/blog/custom-grafana-dashboards-red-hat-openshift-container-platform-4

# Re-worked as https://github.com/kevchu3/openshift4-grafana and forked