---
kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    dashboards: {{ .Values.grafana_dashboard_name }}
  name: {{ .Values.grafana_dashboard_name }}
  namespace: {{ .Values.namespace_to_deploy_grafana_and_dashboards }}
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: redhat
      admin_user: admin
  route:
    spec:
      host: {{ .Values.grafana_dashboard_route_hostname }}
      port:
        targetPort: grafana
      tls:
        termination: edge
      to:
        kind: Service
        name: {{ .Values.grafana_dashboard_name }}-service
        weight: 100
      wildcardPolicy: None
