---
kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    dashboards: {{ .Values.grafana_dashboard_name }}
  name: {{ .Values.grafana_dashboard_name }}
  namespace: {{ .Values.namespace_to_deploy_grafana_and_dashboards }}
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      # These values can be commented out, this way you can specify your own secret:
      # kind: Secret
      # apiVersion: v1
      # metadata:
      #   name: grafana-openshift-admin-credentials
      #   namespace: monitoring-grafana-dashboards
      # data:
      #   GF_SECURITY_ADMIN_PASSWORD: dD...Ug=
      #   GF_SECURITY_ADMIN_USER: Y...=
      # type: Opaque
      admin_password: redhat
      admin_user: admin
  route:
    spec:
      host: {{ .Values.grafana_dashboard_route_hostname }}
      port:
        targetPort: grafana
      tls:
        termination: edge
      to:
        kind: Service
        name: {{ .Values.grafana_dashboard_name }}-service
        weight: 100
      wildcardPolicy: None
