---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: grafana-operator
  namespace: {{ .Values.namespace_to_deploy_grafana_and_dashboards }}
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.grafana_operator_version }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: grafana
  namespace: {{ .Values.namespace_to_deploy_grafana_and_dashboards }}
spec:
  targetNamespaces:
   - {{ .Values.namespace_to_deploy_grafana_and_dashboards }}
