---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.grafana_dashboard_name }}-route-nooauth
  namespace: {{ .Values.namespace_to_deploy_grafana_and_dashboards }}
spec:
  host: {{ .Values.grafana_dashboard_route_hostname_no_oauth }}
  to:
    kind: Service
    name: {{ .Values.grafana_dashboard_name }}-service
    weight: 100
  port:
    targetPort: grafana
  tls:
    termination: edge
  wildcardPolicy: None
