apiVersion: v2
name: ArgoCD main Helm Chart for Grafana dashboard configuration
description: A Helm chart for ArgoCD
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: base
  version: "1.0.0"
  repository: "file://base/"
- name: custom-dashboards
  version: "1.0.0"
  repository: "file://custom_dashboards/"
- name: native-openshift-dashboards
  version: "1.0.0"
  repository: "file://native_openshift_dashboards/"

