apiVersion: v2
name: ArgoCD main Helm Chart for Grafana dashboard configuration
description: A Helm chart for ArgoCD
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: "Base Grafana installation"
  version: "1.0.0"
  repository: "file://base/"
- name: "Custom dashboards"
  version: "1.0.0"
  repository: "file://custom_dashboards/"
- name: "Native OpenShift dashboards"
  version: "1.0.0"
  repository: "file://native_openshift_dashboards/"

